version: "1.0"
info:
  model: int-scaffold
packages:
- name: IDNDemoProject
  gitServerName: johnpcarter
  gitUrl: https://github.com/johnpcarter/IDNDemoProject
  gitUsername: johnpcarter
  gitBranch: main
